use crate::error::{ParseError, SyntaxError};
use crate::location::Location;
use crate::package::{
    FilePackageInfo, FileScope, PackageAnalysis, PackageContext, PackageFileAnalysis,
    make_package_analysis, summarize_package_info,
};
use crate::roxygen::{extract_roxygen_examples, remap_roxygen_fix, remap_roxygen_range};
use crate::suppression::SuppressionManager;
use crate::vcs::check_version_control;
use air_fs::relativize_path;
use air_r_parser::RParserOptions;
use air_r_syntax::RSyntaxNode;
use anyhow::{Context, Result};
use biome_rowan::{TextRange, TextSize};
use rayon::prelude::*;
use std::collections::HashMap;
use std::fs;
use std::path::Path;
use std::path::PathBuf;
use std::sync::Arc;

use crate::analyze::document::check_document;
use crate::analyze::expression::check_expression;
pub use crate::checker::Checker;
use crate::config::Config;
use crate::diagnostic::*;
use crate::fix::*;
use crate::rule_set::RuleSet;
use crate::utils::*;

pub fn check(config: Config) -> Vec<(String, Result<Vec<Diagnostic>, anyhow::Error>)> {
    let (pkg_contexts, file_pkg_info) = summarize_package_info(&config.paths);

    let namespace_contents: HashMap<PathBuf, String> = pkg_contexts
        .iter()
        .filter_map(|(root, ctx)| {
            ctx.namespace_content
                .as_ref()
                .map(|c| (root.clone(), c.clone()))
        })
        .collect();
    let pkg = make_package_analysis(&config.paths, &config, &namespace_contents);
    let pkg_contexts = Arc::new(pkg_contexts);
    let file_pkg_info = Arc::new(file_pkg_info);

    // Ensure that all paths are covered by VCS. This is conservative because
    // technically we could apply fixes on those that are covered by VCS and
    // error for the others, but I'd rather be on the safe side and force the
    // user to deal with that before applying any fixes.
    if (config.apply_fixes || config.apply_unsafe_fixes) && !config.paths.is_empty() {
        let path_strings: Vec<String> = config.paths.iter().map(relativize_path).collect();
        if let Err(e) = check_version_control(&path_strings, &config) {
            let first_path = path_strings.first().unwrap().clone();
            return vec![(first_path, Err(e))];
        }
    }

    // Wrap config and package analysis in Arc to avoid expensive clones in parallel execution
    let config = Arc::new(config);
    let pkg = Arc::new(pkg);

    config
        .paths
        .par_iter()
        .map(|file| {
            let res = check_path(
                file,
                Arc::clone(&config),
                Arc::clone(&pkg),
                Arc::clone(&pkg_contexts),
                Arc::clone(&file_pkg_info),
            );
            (relativize_path(file), res)
        })
        .collect()
}

pub fn check_path(
    path: &PathBuf,
    config: Arc<Config>,
    pkg: Arc<PackageAnalysis>,
    pkg_contexts: Arc<HashMap<PathBuf, PackageContext>>,
    file_pkg_info: Arc<HashMap<PathBuf, FilePackageInfo>>,
) -> Result<Vec<Diagnostic>, anyhow::Error> {
    if config.apply_fixes || config.apply_unsafe_fixes {
        lint_fix(path, config, pkg, pkg_contexts, file_pkg_info)
    } else {
        lint_only(path, config, pkg, pkg_contexts, file_pkg_info)
    }
}

/// Filter `config.rules_to_apply` down to the rules that apply to `path` after
/// accounting for `[lint.per-file-ignores]`.
fn effective_rules_for_file(config: &Config, path: &Path) -> RuleSet {
    if config.per_file_ignores.is_empty() {
        return config.rules_to_apply.clone();
    }
    let ignored = config.per_file_ignores.ignored_rules(path);
    config
        .rules_to_apply
        .iter()
        .filter(|rule| !ignored.contains(rule))
        .collect()
}

pub fn lint_only(
    path: &PathBuf,
    config: Arc<Config>,
    pkg: Arc<PackageAnalysis>,
    pkg_contexts: Arc<HashMap<PathBuf, PackageContext>>,
    file_pkg_info: Arc<HashMap<PathBuf, FilePackageInfo>>,
) -> Result<Vec<Diagnostic>, anyhow::Error> {
    let path = relativize_path(path);
    let contents = fs::read_to_string(Path::new(&path))
        .with_context(|| format!("Failed to read file: {path}"))?;

    // Files starting with "# Generated by" are ignored but they still
    // contribute use sites to cross-file analysis since the scan in
    // `make_package_analysis` runs independently.
    if crate::fs::looks_generated(&contents) {
        return Ok(Vec::new());
    }

    let checks = get_checks(
        &contents,
        &PathBuf::from(&path),
        &config,
        &pkg,
        &pkg_contexts,
        &file_pkg_info,
        // lint-only: on-disk contents match the cached index, so reuse it.
        true,
    )
    .with_context(|| format!("Failed to get checks for file: {path}"))?;

    Ok(checks)
}

pub fn lint_fix(
    path: &PathBuf,
    config: Arc<Config>,
    pkg: Arc<PackageAnalysis>,
    pkg_contexts: Arc<HashMap<PathBuf, PackageContext>>,
    file_pkg_info: Arc<HashMap<PathBuf, FilePackageInfo>>,
) -> Result<Vec<Diagnostic>, anyhow::Error> {
    // Rmd/Qmd files never get autofixes applied.
    if crate::fs::has_rmd_extension(path) {
        return lint_only(path, config, pkg, pkg_contexts, file_pkg_info);
    }

    let path = relativize_path(path);

    let mut checks: Vec<Diagnostic>;

    loop {
        let contents = fs::read_to_string(Path::new(&path))
            .with_context(|| format!("Failed to read file: {path}",))?;

        // Skip auto-generated files: no diagnostics, no fixes.
        if crate::fs::looks_generated(&contents) {
            return Ok(Vec::new());
        }

        checks = get_checks(
            &contents,
            &PathBuf::from(&path),
            &config,
            &pkg,
            &pkg_contexts,
            &file_pkg_info,
            // Fix mode rewrites the file between iterations, so the on-disk
            // contents (and the index the pre-pass cached from them) drift from
            // the in-memory `contents`; rebuild the index rather than reuse it.
            false,
        )
        .with_context(|| format!("Failed to get checks for file: {path}",))?;

        let has_fixable = checks
            .iter()
            .any(|d| d.has_safe_fix() || d.has_unsafe_fix());
        if !has_fixable {
            break;
        }

        let fixed_text = apply_fixes(&checks, &contents);

        // No progress was made (e.g. all fixes overlap), stop to avoid an
        // infinite loop.
        if fixed_text == contents {
            break;
        }

        fs::write(&path, fixed_text).with_context(|| format!("Failed to write file: {path}",))?;
    }

    Ok(checks)
}

// Takes the R code as a string, parses it, and obtains a (possibly empty)
// vector of `Diagnostic`s.
//
// If there are diagnostics to report, this is also where their range in the
// string is converted to their location (row, column).
pub fn get_checks(
    contents: &str,
    file: &Path,
    config: &Config,
    pkg: &PackageAnalysis,
    pkg_contexts: &HashMap<PathBuf, PackageContext>,
    file_pkg_info: &HashMap<PathBuf, FilePackageInfo>,
    use_cached_index: bool,
) -> Result<Vec<Diagnostic>> {
    if crate::fs::has_rmd_extension(file) {
        // Same cache validity rule as the per-file indices below: shareable
        // while the run's caches match the disk, fresh when they may drift.
        let source_cache = if use_cached_index {
            pkg.source_index_cache.clone()
        } else {
            jarl_semantic::SourceIndexCache::new()
        };
        return get_checks_rmd(contents, file, config, source_cache);
    }

    let parser_options = RParserOptions::default();
    let parsed = air_r_parser::parse(contents, parser_options);

    // The parser recovers from syntax errors: each failed statement is wrapped
    // in a bogus node and the rest of the file is parsed normally, so we can
    // still lint the valid code. Autofixes are disabled for the whole file
    // because edits computed around broken code are not reliable.
    let has_parse_errors = parsed.has_error();

    let syntax = &parsed.syntax();
    let expressions = &parsed.tree().expressions();

    let suppression = SuppressionManager::from_node(syntax, contents);

    let mut checker = Checker::new(suppression, config.rule_options.clone());
    // Drop any rules ignored for this file via `[lint.per-file-ignores]`.
    checker.rule_set = effective_rules_for_file(config, file);
    checker.minimum_r_version = config.minimum_r_version;

    // Build the semantic index for use-def-based rules. `source("path")`
    // calls inject `DefinitionKind::Import` entries via JarlImportsResolver;
    // the complementary "names read by sourced files" path is still handled
    // inside `SemanticInfo`.
    //
    // When `unused_object` runs, the cross-file pre-pass already built this
    // file's index (with the same resolver) and stored it in `pkg.file_indices`;
    // reuse it rather than rebuilding. The pre-pass reads from disk, so the
    // cache is only valid in lint-only mode — fix mode rewrites the file
    // between passes, so it always rebuilds from the in-memory contents.
    //
    // Building (when not cached) happens here, in the parallel per-file pass,
    // rather than via the shared `AnalysisDb`: oak's salsa database is `Send`
    // but not `Sync`, so it can't be borrowed across rayon worker threads.
    // The source-target memo follows the same validity rule as the per-file
    // index cache: sharable while the run's caches match the disk, fresh when
    // they may drift (fix mode, LSP buffers).
    if use_cached_index {
        checker.source_index_cache = pkg.source_index_cache.clone();
    }
    let owned_semantic;
    let semantic: &oak_semantic::semantic_index::SemanticIndex = match use_cached_index
        .then(|| pkg.file_indices.get(file))
        .flatten()
    {
        Some(cached) => cached,
        None => {
            owned_semantic = oak_semantic::build_index(
                &parsed.tree(),
                jarl_semantic::JarlImportsResolver::with_cache(
                    file,
                    checker.source_index_cache.clone(),
                ),
            );
            &owned_semantic
        }
    };
    checker.file_path = file.to_path_buf();

    // Wire up package context for package-specific rules.
    get_package_info(
        &mut checker,
        file,
        semantic,
        config,
        pkg_contexts,
        file_pkg_info,
    );

    // Look up per-file data from PackageAnalysis
    let package_file = PackageFileAnalysis::for_file(pkg, file);

    // We run checks at expression-level. This gathers all violations, no matter
    // whether they are suppressed or not. They are filtered out in the next
    // step (this is also Ruff's approach).
    for expr in expressions {
        check_expression(&expr, &mut checker)?;
    }

    // Lint R code inside roxygen @examples / @examplesIf sections.
    // Collected before check_document so that suppression filtering (which
    // runs inside check_document) can match `# jarl-ignore` comments in
    // the main file against violations found in roxygen examples.
    if config.check_roxygen
        && contents.contains("#'")
        && contents.contains("@examples")
        && matches!(
            file_pkg_info.get(file),
            Some(FilePackageInfo::InPackage { scope: FileScope::R, .. })
        )
    {
        let roxygen_diagnostics = get_checks_roxygen(syntax, file, config, contents)?;
        checker.diagnostics.extend(roxygen_diagnostics);
    }

    // We run checks at document-level. This includes checks that require the
    // entire document (like top-level unreachable code) and comment-related
    // checks (blanket, unexplained, misplaced, misnamed, unused suppressions).
    // This must run after checking expressions because we filter out those that
    // are unused.
    check_document(
        expressions,
        syntax,
        &mut checker,
        &package_file,
        Some(semantic),
    )?;

    // Some rules have a fix available in their implementation but do not have
    // fix in the config, for instance because they are part of the "unfixable"
    // arg or not part of the "fixable" arg in `jarl.toml`.
    // When we get all the diagnostics with check_expression() above, we don't
    // pay attention to whether the user wants to fix them or not. Adding this
    // step here is a way to filter those fixes out before calling apply_fixes().
    let rules_without_fix = checker
        .rule_set
        .iter()
        .filter(|x| x.has_no_fix())
        .map(|x| x.name().to_string())
        .collect::<Vec<String>>();

    let diagnostics: Vec<Diagnostic> = checker
        .diagnostics
        .into_iter()
        .map(|mut x| {
            x.filename = file.to_path_buf();
            // Check if fix should be skipped based on fixable/unfixable settings
            if rules_without_fix.contains(&x.message.name) {
                x.fix = Fix::empty();
            }
            // Also check against unfixable set from config
            if config.unfixable.contains(&x.message.name) {
                x.fix = Fix::empty();
            }
            // If fixable is specified, only allow those rules to have fixes
            if let Some(ref fixable_set) = config.fixable
                && !fixable_set.contains(&x.message.name)
            {
                x.fix = Fix::empty();
            }
            // TODO: this should be removed once comments in nodes are better
            // handled, #95
            if x.fix.to_skip {
                x.fix = Fix::empty();
            }
            if has_parse_errors {
                x.fix = Fix::empty();
            }
            x
        })
        .collect();

    let loc_new_lines = find_new_lines(syntax)?;
    let diagnostics = compute_lints_location(diagnostics, &loc_new_lines);

    if has_parse_errors {
        let syntax_errors = collect_syntax_errors(&parsed, contents);
        return Err(ParseError {
            filename: file.to_path_buf(),
            diagnostics,
            syntax_errors,
        }
        .into());
    }

    Ok(diagnostics)
}

/// Convert the parser's diagnostics (message + span) into the `SyntaxError`s
/// carried by [`ParseError`], resolving each span to a (row, column) location.
///
/// Locations are computed against `contents` (not the parsed tree) because
/// `find_new_lines` reads the serialized tree, which can be truncated once the
/// parser has recovered from an error, throwing later offsets off.
fn collect_syntax_errors(parsed: &air_r_parser::Parse, contents: &str) -> Vec<SyntaxError> {
    // `Diagnostic::location` (the trait method) is the only public accessor for
    // a `ParseDiagnostic`'s span.
    use biome_diagnostics::Diagnostic as _;

    let loc_new_lines = crate::utils::find_new_lines_from_content(contents);

    parsed
        .diagnostics()
        .iter()
        .map(|diagnostic| {
            // The span is optional on `ParseDiagnostic`, but every diagnostic
            // the R parser builds is given a range, so this only ever falls
            // back if that changes upstream.
            let range = diagnostic.location().span.map_or_else(
                || end_of_content(contents),
                |range| normalize_eof_range(contents, range),
            );
            let start: usize = range.start().into();
            let (row, col) = find_row_col(start, &loc_new_lines);
            SyntaxError {
                message: diagnostic.message.to_string(),
                range,
                location: Location::new(row, col),
            }
        })
        .collect()
}

/// Move an end-of-file error span back to the end of the last line with
/// content.
///
/// Parser errors at EOF are zero-width spans sitting past the final newline, on
/// an empty line. annotate-snippets renders those as an empty snippet, and the
/// end of the last real line is the more useful place to point at anyway.
fn normalize_eof_range(contents: &str, range: TextRange) -> TextRange {
    if range.is_empty() && usize::from(range.start()) == contents.len() {
        return end_of_content(contents);
    }
    range
}

/// The empty range at the end of the last line with content.
fn end_of_content(contents: &str) -> TextRange {
    let trimmed = contents.trim_end_matches(['\n', '\r']).len();
    let pos = TextSize::from(trimmed as u32);
    TextRange::new(pos, pos)
}

/// Populate package context on the checker from pre-computed data.
///
/// For files inside an R package, copies the pre-computed `PackageContext`
/// fields. For scripts, harvests `library()`/`require()` calls from the
/// semantic index.
fn get_package_info(
    checker: &mut Checker,
    file: &Path,
    semantic: &oak_semantic::semantic_index::SemanticIndex,
    config: &Config,
    pkg_contexts: &HashMap<PathBuf, PackageContext>,
    file_pkg_info: &HashMap<PathBuf, FilePackageInfo>,
) {
    match file_pkg_info.get(file) {
        Some(FilePackageInfo::InPackage { package_root, .. }) => {
            if let Some(ctx) = pkg_contexts.get(package_root) {
                checker.loaded_packages = ctx.loaded_packages.clone();
                checker.import_from = ctx.import_from.clone();
                checker.namespace_exports = ctx.namespace_exports.clone();
            }
        }
        _ => checker.loaded_packages = script_packages(semantic),
    }
    checker.package_cache = config.package_cache.clone();
}

/// The packages a file outside an R package can reach: the always-available
/// defaults plus whatever it attaches itself.
fn script_packages(semantic: &oak_semantic::semantic_index::SemanticIndex) -> Vec<String> {
    let mut packages: Vec<String> = crate::checker::DEFAULT_PACKAGES
        .iter()
        .map(|s| s.to_string())
        .collect();
    packages.extend(top_level_attached_packages(semantic));
    packages
}

/// Collect the packages a file attaches with `library()`/`require()`, in load
/// order, deduplicated. Oak counts a call only when it runs as the file loads,
/// so calls inside a function body are excluded (their attachment isn't
/// statically guaranteed) while calls inside a top-level `if`/loop are kept (R
/// runs top-level code sequentially, so the attach is visible to later code if
/// the branch runs).
fn top_level_attached_packages(
    semantic: &oak_semantic::semantic_index::SemanticIndex,
) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    for package in semantic.attached_packages() {
        if !out.iter().any(|p| p == package) {
            out.push(package.to_string());
        }
    }
    out
}

/// Lint R code inside roxygen `@examples` and `@examplesIf` sections.
///
/// Each examples section is extracted, parsed as standalone R code, and linted.
/// Diagnostic byte ranges are remapped to point to the correct position in the
/// original file. Autofixes are disabled because the `#'` prefix makes
/// position-based edits unsafe.
fn get_checks_roxygen(
    syntax: &RSyntaxNode,
    file: &Path,
    config: &Config,
    contents: &str,
) -> Result<Vec<Diagnostic>> {
    let chunks = extract_roxygen_examples(syntax, contents);
    let mut all_diagnostics: Vec<Diagnostic> = Vec::new();

    for chunk in &chunks {
        let parsed = air_r_parser::parse(&chunk.code, RParserOptions::default());
        if parsed.has_error() {
            // Examples may contain pseudo-code, \dontrun{} wrappers, etc.
            continue;
        }

        let expressions = &parsed.tree().expressions();
        let syntax = parsed.syntax();
        let suppression = SuppressionManager::from_node(&syntax, &chunk.code);
        let has_suppressions = suppression.has_any_suppressions;
        let mut checker = Checker::new(suppression, config.rule_options.clone());
        checker.rule_set = effective_rules_for_file(config, file);
        checker.minimum_r_version = config.minimum_r_version;

        for expr in expressions {
            check_expression(&expr, &mut checker)?;
        }

        // Only run document-level checks if the examples code has inline
        // suppression comments. Most examples don't, and check_document is
        // otherwise unnecessary here (no package-level analysis, no
        // suppression-related diagnostics to report).
        if has_suppressions {
            check_document(
                expressions,
                &syntax,
                &mut checker,
                &PackageFileAnalysis::default(),
                None,
            )?;
        }

        for mut d in checker.diagnostics {
            d.range = remap_roxygen_range(d.range, chunk);
            if config.fix_roxygen {
                d.fix = remap_roxygen_fix(&d.fix, chunk, contents);
            } else {
                d.fix = Fix::empty();
            }
            d.filename = file.to_path_buf();
            all_diagnostics.push(d);
        }
    }

    Ok(all_diagnostics)
}

/// Names read by R code that belongs to the document but isn't in the virtual
/// source, and so is invisible to the use-def analysis:
///
/// - inline spans in the prose (`` `r mean(x)` ``), which aren't linted but do
///   run when the document is rendered;
/// - chunks dropped because they don't parse, which have nothing to analyze
///   but still run — unless they wouldn't have run anyway (`eval = FALSE`),
///   in which case they are left out here too;
/// - chunk options (`{r, fig.cap = my_caption}`, `#| eval: !expr run_it`),
///   which knitr evaluates for *every* chunk, including one whose own code
///   never runs.
///
/// An object named in any of them is used. Erring towards collecting too many
/// names is deliberate: a name harvested here can only silence a diagnostic,
/// whereas a read missed here invents one.
fn reads_outside_chunk_code(
    contents: &str,
    chunks: &[crate::rmd::RCodeChunk],
    skipped: &[usize],
) -> std::collections::HashSet<String> {
    let mut names: std::collections::HashSet<String> = std::collections::HashSet::new();

    let inline = crate::rmd::extract_inline_r_code(contents, chunks);
    let dropped = skipped
        .iter()
        .map(|i| &chunks[*i])
        .filter(|chunk| chunk.evaluated)
        .map(|chunk| chunk.code.as_str());
    for code in inline.into_iter().chain(dropped) {
        names.extend(all_symbols(code));
    }

    for chunk in chunks {
        for snippet in crate::rmd::chunk_option_code(chunk) {
            names.extend(read_symbols(&snippet));
        }
    }

    names
}

/// Every identifier-shaped word in `code`, whatever it stands for.
/// [`scan_symbols`] over-collects by design; see there.
fn all_symbols(code: &str) -> impl Iterator<Item = String> {
    scan_symbols(code).into_keys()
}

/// The names `code` *reads*, leaving out the names of named arguments — for
/// chunk options, the difference between the object `fig.cap = my_caption`
/// reads and the option it sets. Falls back to [`all_symbols`] when the
/// snippet doesn't parse, since then the two can't be told apart and missing a
/// read is the more damaging error.
fn read_symbols(code: &str) -> Vec<String> {
    let parsed = air_r_parser::parse(code, RParserOptions::default());
    if parsed.has_error() {
        return all_symbols(code).collect();
    }

    parsed
        .syntax()
        .descendants()
        .filter(|node| node.kind() == air_r_syntax::RSyntaxKind::R_IDENTIFIER)
        .filter(|node| {
            node.parent().is_none_or(|parent| {
                parent.kind() != air_r_syntax::RSyntaxKind::R_ARGUMENT_NAME_CLAUSE
            })
        })
        .map(|node| node.text_trimmed().to_string())
        .collect()
}

/// Lint an Rmd/Qmd file by concatenating R code chunks into a virtual R
/// string and running the normal linting pipeline on it.
///
/// Key differences from regular R file linting:
/// - No autofix (Quarto code annotations make position-based edits unsafe)
/// - `#| jarl-ignore-chunk:` YAML blocks are translated to `# jarl-ignore-start`
///   / `# jarl-ignore-end` pairs before linting
/// - Chunks with parse errors are dropped, without a diagnostic of their own
/// - Diagnostic ranges are remapped from virtual-string offsets to original file offsets
///
/// Knitr evaluates every chunk of a document in one R session, in document
/// order, which is exactly what the concatenation models — so use-def rules
/// like `unused_object` see an object assigned in one chunk and read in a
/// later one as used. The two ways a document departs from that model are
/// handled explicitly: code that runs but isn't in the virtual source
/// contributes reads (see [`reads_outside_chunk_code`]), and code that is in the
/// virtual source but doesn't run (`eval = FALSE` chunks) contributes
/// neither reads nor definitions.
fn get_checks_rmd(
    contents: &str,
    file: &Path,
    config: &Config,
    source_cache: jarl_semantic::SourceIndexCache,
) -> Result<Vec<Diagnostic>> {
    let chunks = crate::rmd::extract_r_chunks(contents);
    let crate::rmd::VirtualSource {
        source: virtual_source,
        offset_map,
        skipped,
        unevaluated,
    } = crate::rmd::build_virtual_r_source(&chunks);

    if virtual_source.trim().is_empty() {
        return Ok(Vec::new());
    }

    let parsed = air_r_parser::parse(&virtual_source, RParserOptions::default());
    let has_parse_errors = parsed.has_error();

    let syntax = parsed.syntax();
    let suppression = SuppressionManager::from_node(&syntax, &virtual_source);
    let mut checker = Checker::new(suppression, config.rule_options.clone());
    checker.rule_set = effective_rules_for_file(config, file);
    checker.minimum_r_version = config.minimum_r_version;
    checker.file_path = file.to_path_buf();
    checker.source_index_cache = source_cache.clone();
    // A chunk marked `eval = FALSE` is still linted, but it never runs, so it
    // defines nothing and reads nothing.
    checker.unevaluated_ranges = unevaluated;

    // The document's own path anchors `source()` resolution, so a chunk
    // sourcing a helper next to the document resolves it there.
    let semantic = oak_semantic::build_index(
        &parsed.tree(),
        jarl_semantic::JarlImportsResolver::with_cache(file, source_cache),
    );
    // A document is never package code, so it reaches the same packages a
    // script does: the defaults plus what its chunks attach.
    checker.loaded_packages = script_packages(&semantic);
    checker.package_cache = config.package_cache.clone();

    let expressions = &parsed.tree().expressions();
    for expr in expressions {
        check_expression(&expr, &mut checker)?;
    }
    // check_document runs suppression filtering internally, so
    // checker.diagnostics is the post-suppression list after this call.
    // Rmd chunks don't participate in package-level analysis; the one
    // package-level input that does apply is the set of names read outside the
    // chunks, which keeps objects the prose uses from looking unused.
    let package_file = PackageFileAnalysis {
        cross_file_used: reads_outside_chunk_code(contents, &chunks, &skipped),
        ..PackageFileAnalysis::default()
    };
    check_document(
        expressions,
        &syntax,
        &mut checker,
        &package_file,
        Some(&semantic),
    )?;

    // Remap ranges from virtual-string offsets to original Rmd file offsets.
    let diagnostics: Vec<Diagnostic> = checker
        .diagnostics
        .into_iter()
        .map(|mut d| {
            d.filename = file.to_path_buf();
            d.fix = Fix::empty();
            d.range = offset_map.remap_range(d.range);
            d
        })
        .collect();

    let loc_new_lines = crate::utils::find_new_lines_from_content(contents);
    let diagnostics = compute_lints_location(diagnostics, &loc_new_lines);

    if has_parse_errors {
        // Rmd parse errors are reported against the combined virtual source;
        // mapping arbitrary error spans back to the original file is unreliable,
        // so we report only the generic summary here (no per-error snippets).
        return Err(ParseError {
            filename: file.to_path_buf(),
            diagnostics,
            syntax_errors: Vec::new(),
        }
        .into());
    }

    Ok(diagnostics)
}

#[cfg(test)]
mod tests {
    use crate::utils_test::*;
    use insta::assert_snapshot;

    #[test]
    fn test_fix_does_not_introduce_new_lints() {
        // Fixing `outer_negation` on this code would produce
        // `expect_true(!any(is.na(x)))`, which introduced new
        // `expect_not` and `any_is_na` lints. The fix loop should keep
        // going until the code is fully clean.
        assert_snapshot!(
            get_fixed_text(
                vec!["expect_true(all(!is.na(x)))"],
                "ALL",
                None
            ),
            @"
        OLD:
        ====
        expect_true(all(!is.na(x)))
        NEW:
        ====
        expect_false(anyNA(x))
        "
        );
    }

    #[test]
    fn test_overlapping_fixes_do_not_corrupt() {
        // `fixed_regex` replaces the whole call (adding `, fixed = TRUE`)
        // while `quotes` replaces just the string inside it. The nested
        // fix must be skipped in the first pass and applied in the next
        // iteration, not applied on stale offsets.
        assert_snapshot!(
            get_fixed_text(
                vec!["grepl('/', repo)"],
                "ALL",
                None
            ),
            @r#"
        OLD:
        ====
        grepl('/', repo)
        NEW:
        ====
        grepl("/", repo, fixed = TRUE)
        "#
        );
    }
}
