//! Access to the rule documentation embedded at build time.
//!
//! The `rule_doc` function is generated by `build.rs` from the markdown files
//! in `docs/rules/`. See that build script for details.

include!(concat!(env!("OUT_DIR"), "/rule_docs.rs"));
