.extract_documentation <- function(rs_file, .ref = NULL) {
  rust_script <- readLines(rs_file)

  doc_markers <- list(
    start = grep("^/// <!-- docs: start -->", rust_script),
    end = grep("^/// <!-- docs: end -->", rust_script)
  )

  if (identical(lengths(doc_markers), c(start = 0L, end = 0L))) {
    return(NULL)
  } else if (!identical(lengths(doc_markers), c(start = 1L, end = 1L))) {
    if (is.null(.ref)) {
      .ref <- rs_file
    }
    stop("Documentation markers in `", .ref, "` are malformed.")
  }

  gsub(
    "^///\\s?",
    "",
    rust_script[(doc_markers$start + 1):(doc_markers$end - 1)]
  )
}

create_rule_md <- function(rule, lints_dir) {
  # rule meta
  rule_name <- basename(rule)
  rs_file <- file.path(lints_dir, rule, paste0(rule_name, ".rs"))
  options_rs <- file.path(lints_dir, rule, "options.rs")

  if (!file.exists(rs_file)) {
    stop(
      c(
        "Cannot find rust script for rule `",
        rule_name,
        "`\nExpected: ",
        rs_file
      )
    )
  }

  doc_content <- .extract_documentation(rs_file, rule_name)

  if (is.null(doc_content)) {
    return(FALSE)
  }

  # inspect version metadata
  version_loc <- grep("^Version added:", doc_content)

  if (length(version_loc) == 0) {
    stop("No 'version added' meta in rule `", rule_name, "`.")
  } else if (length(version_loc) != 1) {
    stop("Multiple 'version added' meta in rule `", rule_name, "`.")
  }

  version_added <- gsub(
    ".*(\\d+\\.\\d+\\.\\d+).*",
    "\\1",
    doc_content[version_loc]
  )

  if (!grepl("^\\d+\\.\\d+\\.\\d+$", version_added)) {
    stop("The 'version added' meta for rule `", rule_name, "` is malformed.")
  }

  # make documentation output
  rule_doc <- list(
    title = paste0("# ", rule_name, "\n"),
    version_tag = paste0(
      "::: {.callout-note title=\"Added in ",
      version_added,
      "\" .low-opacity}\n:::"
    ),
    main_content = doc_content[-version_loc]
  )

  if (file.exists(options_rs)) {
    options_content <- .extract_documentation(
      options_rs,
      file.path(rule_name, "options.rs")
    )
    if (!is.null(options_content)) {
      rule_doc$options <- list(
        sep = "\n---\n",
        title = "## Configuration options\n",
        generic_content = paste0(
          "The operation of `",
          rule_name,
          "` can be customised in the ",
          "[configuration file](../reference/config-file.md).\n"
        ),
        rule_options = options_content
      )
    }
  }

  writeLines(unlist(rule_doc), paste0("docs/rules/", rule_name, ".md"))

  return(TRUE)
}

create_config_md <- function(
  lints_dir,
  config_base = "docs/reference/_config-file.md",
  config_out = "docs/reference/config-file.md"
) {
  config_content <- readLines(config_base)

  options_files <- list.files(
    lints_dir,
    pattern = "options\\.rs$",
    recursive = TRUE
  )

  options_rules <- basename(dirname(options_files))

  config_rules <- c(
    "## Rule-specific arguments",
    "",
    "The operation of some rules can be customised with arguments in the",
    "configuration file, see the relevant rule documentation page for details:",
    "",
    paste0(
      "* ",
      paste0(
        "[`",
        options_rules,
        "`](../rules/",
        options_rules,
        ".md#configuration-options)"
      )
    )
  )

  header_content <- c(
    "<!-- ============ -->",
    "<!-- THIS FILE IS AUTOMATICALLY GENERATED. -->",
    "<!-- MODIFY THE DOCS/REFERENCE/_CONFIG-FILE.MD INSTEAD. -->",
    "<!-- ============ -->"
  )

  new_config_content <- c(header_content, "", config_content, "", config_rules)

  writeLines(new_config_content, config_out)
}
