# When we make a new release of Jarl, we also trigger a new release in
# `jarl-pre-commit`. This is because the `rev` parameter in the pre-commit
# file will fetch the matching version of Jarl so that everyone using the
# same pre-commit file also uses the same version of Jarl.

name: Update pre-commit

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

permissions:
  contents: read

jobs:
  update-pre-commit:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.JARL_DISPATCH_PRE_COMMIT }}
    steps:
      - name: Get release tag
        id: tag
        run: |
          TAG=$(gh api repos/${{ github.repository }}/releases/latest --jq '.tag_name')
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Update jarl-pre-commit
        env:
          TAG: ${{ steps.tag.outputs.tag }}
        run: |
          gh api repos/etiennebacher/jarl-pre-commit/dispatches \
            -f event_type=jarl-release \
            -f "client_payload[version]=$TAG"
